# Generated by Django 4.2 on 2026-03-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('SINGLE_FILE', 'Single File'), ('FOLDER', 'Folder'), ('CODE_SNIPPET', 'Code Snippet')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('file_count', models.IntegerField(default=0)),
                ('total_smells_found', models.IntegerField(default=0)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/files/')),
                ('uploaded_folder', models.CharField(blank=True, max_length=500)),
                ('code_snippet', models.TextField(blank=True)),
                ('results_json', models.JSONField(blank=True, default=dict)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Memory used in MB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSmellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('refactoring_tip', models.TextField(blank=True)),
                ('example_code', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'code_smell_types',
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('RANDOM_FOREST', 'Random Forest'), ('GRADIENT_BOOSTING', 'Gradient Boosting'), ('ADA_BOOST', 'AdaBoost'), ('DECISION_TREE', 'Decision Tree'), ('SVM', 'Support Vector Machine'), ('NEURAL_NETWORK', 'Neural Network'), ('LOGISTIC_REGRESSION', 'Logistic Regression')], default='RANDOM_FOREST', max_length=20)),
                ('model_file', models.FileField(upload_to='models/')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('encoder_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('mcc', models.FloatField(blank=True, null=True)),
                ('dataset_used', models.CharField(blank=True, max_length=255)),
                ('features_used', models.TextField(blank=True, help_text='Comma-separated list of features')),
                ('training_time', models.FloatField(blank=True, help_text='Training time in seconds', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trained_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmellDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('line_start', models.IntegerField(blank=True, null=True)),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('loc', models.IntegerField(default=0)),
                ('wmc', models.IntegerField(default=0)),
                ('cbo', models.IntegerField(default=0)),
                ('tcc', models.FloatField(default=0.0)),
                ('lcom', models.IntegerField(default=0)),
                ('rfc', models.IntegerField(default=0)),
                ('complexity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detector.analysisjob')),
                ('smell_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.codesmelltype')),
            ],
            options={
                'db_table': 'smell_detection_results',
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('mcc', models.FloatField()),
                ('cv_scores', models.JSONField(default=list)),
                ('cv_mean', models.FloatField()),
                ('cv_std', models.FloatField()),
                ('confusion_matrix', models.JSONField(default=list)),
                ('classification_report', models.JSONField(default=dict)),
                ('feature_importance', models.JSONField(default=dict)),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('roc_curve_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='detector.trainedmodel')),
            ],
            options={
                'db_table': 'model_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.IntegerField(default=0)),
                ('wmc', models.IntegerField(default=0)),
                ('cbo', models.IntegerField(default=0)),
                ('tcc', models.FloatField(default=0.0)),
                ('lcom', models.IntegerField(default=0)),
                ('rfc', models.IntegerField(default=0)),
                ('complexity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.analysisjob')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metric_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='datasets/')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='model_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detector.trainedmodel'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
